declare module "lucide-react" {
  import { FC, SVGProps } from "react";
  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: number | string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
    color?: string;
  }
  export type Icon = FC<IconProps>;
  export const ActivityIcon: Icon;
  export const AlertTriangleIcon: Icon;
  export const ArrowUpDown: Icon;
  export const Building2Icon: Icon;
  export const CameraIcon: Icon;
  export const ChartBarIcon: Icon;
  export const CheckCircle2Icon: Icon;
  export const CheckIcon: Icon;
  export const ChevronDownIcon: Icon;
  export const ChevronLeftIcon: Icon;
  export const ChevronRightIcon: Icon;
  export const ChevronUpIcon: Icon;
  export const ChevronsLeftIcon: Icon;
  export const ChevronsRightIcon: Icon;
  export const CircleCheckIcon: Icon;
  export const CircleHelpIcon: Icon;
  export const CirclePlusIcon: Icon;
  export const CircleUserRoundIcon: Icon;
  export const ClockIcon: Icon;
  export const Columns3Icon: Icon;
  export const CommandIcon: Icon;
  export const CreditCardIcon: Icon;
  export const DatabaseIcon: Icon;
  export const EllipsisVerticalIcon: Icon;
  export const FileChartColumnIcon: Icon;
  export const FileIcon: Icon;
  export const FileTextIcon: Icon;
  export const FilesIcon: Icon;
  export const FolderIcon: Icon;
  export const GripVerticalIcon: Icon;
  export const HistoryIcon: Icon;
  export const InfoIcon: Icon;
  export const LayoutDashboardIcon: Icon;
  export const ListIcon: Icon;
  export const Loader2Icon: Icon;
  export const LogOutIcon: Icon;
  export const MailIcon: Icon;
  export const MoreHorizontalIcon: Icon;
  export const OctagonXIcon: Icon;
  export const PanelLeftIcon: Icon;
  export const PlugIcon: Icon;
  export const PlayIcon: Icon;
  export const PlusIcon: Icon;
  export const RefreshCwIcon: Icon;
  export const SearchIcon: Icon;
  export const Settings2Icon: Icon;
  export const SettingsIcon: Icon;
  export const ShareIcon: Icon;
  export const Trash2Icon: Icon;
  export const TrendingDownIcon: Icon;
  export const TrendingUpIcon: Icon;
  export const TriangleAlertIcon: Icon;
  export const UserIcon: Icon;
  export const UsersIcon: Icon;
  export const XIcon: Icon;
  export const LockIcon: Icon;
  export const EyeIcon: Icon;
  export const EyeOffIcon: Icon;
  export const ServerIcon: Icon;
  export const ArrowRightIcon: Icon;
  export const ShieldIcon: Icon;
}

